from enum import Enum, unique 

# riase ValueError is the alias are found
@unique
class Mistake(Enum):
    ONE = 1
    TWO = 2
    THREE = 3
    FOUR = 3